# Generated by Django 5.1.7 on 2025-03-24 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('disease_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='disease_detector.diseaserecord')),
            ],
        ),
    ]
