# Generated by Django 5.1.7 on 2025-03-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detector', '0002_diseaseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaserecord',
            name='disease_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='preventive_care',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='probability',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='recommended_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='symptoms_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diseaserecord',
            name='urgency_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
