# Generated by Django 5.1.7 on 2025-03-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detector', '0003_alter_diseaserecord_disease_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaserecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images/'),
        ),
    ]
