# Generated by Django 5.1.7 on 2025-03-25 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detector', '0004_alter_diseaserecord_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diseaserecord',
            name='image',
        ),
    ]
