# Generated by Django 5.1.7 on 2025-03-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_detector', '0005_remove_diseaserecord_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaserecord',
            name='user_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
